apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redisshake-helm.fullname" . }}-config
  labels:
    {{- include "redisshake-helm.labels" . | nindent 4 }}
data:
  sync.toml: |
    {{- .Values.redisshake.syncConfig | nindent 4 }}
  scan.toml: |
    {{- .Values.redisshake.scanConfig | nindent 4 }}
  restore.toml: |
    {{- .Values.redisshake.restoreConfig | nindent 4 }}